name: Workflow API

on:

  push:
    branches:
      # - main
    paths:
      - "src/**"
      - ".github/workflows/workflow-api.yml"
    branches-ignore:
      - release-please--branches--main**

    tags:
      - 202**
      - v[0-9]+.[0-9]+.[0-9]+

  pull_request:
    types: [opened,synchronize]      ## jaise hi PR open hoga to workflow chalega and Validate karega 
    paths:                           ## is path me koi v chnage hoga tb v chalega
      - "src/**"
      - ".github/workflows/workflow-api.yml"

  
      
    
    # branches:
    #   - main

  workflow_dispatch:


jobs:

  call-reusable-workflow:

    uses: abhishekg2244/reusable-workflows/.github/workflows/ci.yml@main

    with:
      app_name: demo-app
      run_lint: true

    secrets:
      DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
